#!/usr/bin/env python3
# Generated by Haiven Compass.
# Do not edit directly.

import shutil, subprocess
from pathlib import Path
root = Path.cwd()
if (root / "package.json").exists() and shutil.which("pnpm"):
    subprocess.run(["pnpm", "haiven:check"], check=True)
elif shutil.which("haiven"):
    subprocess.run(["haiven", "check"], check=True)
else:
    print("haiven check not found. Install @haiven/compass or add pnpm haiven:check.")
